export const weatherConditions: any = {
  Rain: {
    color: '#005BEA',
    title: 'Mưa',
    subtitle: 'Lấy một tách cà phê',
    icon: 'weather-rainy',
    background: require('../Assets/rain.jpg'),
  },
  Clear: {
    color: '#f7b733',
    title: 'Nắng',
    subtitle: 'Nó làm tổn thương mắt tôi',
    icon: 'weather-sunny',
    background: require('../Assets/sunny.jpg'),
  },
  Thunderstorm: {
    color: '#616161',
    title: 'Một cơn bão đang đến',
    subtitle: 'Bởi vì các vị thần đang tức giận',
    icon: 'weather-lightning',
    background: require('../Assets/storm.jpg'),
  },
  Clouds: {
    color: '#966161',
    title: 'Mây',
    subtitle: 'Mợi nơi',
    icon: 'weather-cloudy',
    background: require('../Assets/cloud.jpg'),
  },
  Snow: {
    color: '#00d2ff',
    title: 'Tuyết',
    subtitle: 'Ra ngoài và xây người tuyết cho tôi',
    icon: 'weather-snowy',
    background: require('../Assets/snow.jpg'),
  },
  Drizzle: {
    color: '#076585',
    title: 'Mưa phùn',
    subtitle: 'Một phần mưa',
    icon: 'weather-hail',
    background: require('../Assets/drizzle.jpg'),
  },
  Haze: {
    color: '#66A6FF',
    title: 'Sương mù',
    subtitle: 'Tên gọi khác của mưa cục bộ',
    icon: 'weather-hail',
    background: require('../Assets/haze.jpg'),
  },
  Mist: {
    color: '#3CD3AD',
    title: 'Sương mù',
    subtitle: 'Đừng lang thang trong rừng!',
    icon: 'weather-fog',
    background: require('../Assets/mist.jpg'),
  },
};
